<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;
use App\Models\Staff\Staff;
use App\Models\Activity\TimeSlot;
use App\Models\Admin\AccessLog;
use App\Models\Activity\Activity;
use Carbon\Carbon;

class CoachSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create('fr_FR');

        // Get Coach Role ID
        $coachRoleId = DB::table('pool_schema.roles')->where('role_name', 'coach')->value('role_id');

        if (!$coachRoleId) {
            $this->command->error('Role "coach" not found. Please seed roles first.');
            return;
        }

        // Get Activities
        $activities = Activity::all();
        if ($activities->isEmpty()) {
            $this->command->error('No activities found. Please seed activities first.');
            return;
        }

        $specialties = ['Natation', 'Aquagym', 'Musculation', 'Yoga', 'Fitness'];
        $salaryTypes = ['fixed', 'per_hour', 'per_session'];

        // Create 5 Coaches
        for ($i = 0; $i < 5; $i++) {
            $firstName = $faker->firstName;
            $lastName = $faker->lastName;
            $username = strtolower($firstName . '.' . $lastName);

            $coach = Staff::create([
                'first_name' => $firstName,
                'last_name' => $lastName,
                'username' => $username,
                'password_hash' => '123', // Will be hashed by mutator
                'role_id' => $coachRoleId,
                'is_active' => true,
                'phone_number' => $faker->phoneNumber,
                'email' => $faker->unique()->safeEmail,
                'specialty' => $faker->randomElement($specialties),
                'hiring_date' => $faker->date(),
                'salary_type' => $faker->randomElement($salaryTypes),
                'hourly_rate' => $faker->numberBetween(1000, 3000), // DZD
                'notes' => 'Coach generated by seeder',
            ]);

            $this->command->info("Created Coach: {$coach->full_name}");

            // Create Access Badge for the coach
            $badgeUid = 'COACH-' . mb_strtoupper(mb_substr($coach->first_name, 0, 3)) . '-' . $coach->staff_id;
            
            \App\Models\Member\AccessBadge::create([
                'member_id' => null, // Staff badge, not member
                'staff_id' => $coach->staff_id,
                'badge_uid' => $badgeUid,
                'status' => 'active',
                'issued_at' => now(),
            ]);

            $this->command->info("Created Badge: {$badgeUid}");

            // Create Weekly Planning (TimeSlots)
            // Assign 3-5 slots per week
            $numSlots = rand(3, 5);
            for ($j = 0; $j < $numSlots; $j++) {
                $weekdayId = rand(1, 7); // 1=Monday, 7=Sunday
                $startHour = rand(8, 18);
                $startTime = Carbon::createFromTime($startHour, 0, 0);
                $endTime = $startTime->copy()->addHour();

                TimeSlot::create([
                    'weekday_id' => $weekdayId,
                    'start_time' => $startTime->format('H:i:s'),
                    'end_time' => $endTime->format('H:i:s'),
                    'activity_id' => $activities->random()->activity_id,
                    'coach_id' => $coach->staff_id,
                    'capacity' => 20,
                    'is_blocked' => false,
                    'created_by' => 1, // Assuming admin ID 1 exists
                ]);
            }

            // Create Attendance Logs (Pointages) for the last 30 days
            // Simulate check-ins based on their planning + some random extra
            $startDate = Carbon::now()->subDays(30);
            $endDate = Carbon::now();

            for ($date = $startDate->copy(); $date->lte($endDate); $date->addDay()) {
                $dayOfWeek = $date->dayOfWeekIso;
                
                // Get slots for this day
                $dailySlots = TimeSlot::where('coach_id', $coach->staff_id)
                    ->where('weekday_id', $dayOfWeek)
                    ->get();

                foreach ($dailySlots as $slot) {
                    // 90% chance to attend the scheduled slot
                    if (rand(0, 100) < 90) {
                        // Check-in time: Slot start time +/- random minutes (e.g. -10 to +15 mins)
                        $slotStart = Carbon::parse($slot->start_time);
                        $variance = rand(-10, 15);
                        $checkInTime = $date->copy()->setTimeFromTimeString($slot->start_time)->addMinutes($variance);
                        
                        AccessLog::create([
                            'staff_id' => $coach->staff_id,
                            'access_time' => $checkInTime,
                            'access_decision' => 'granted',
                            'badge_uid' => $badgeUid,
                            // 'slot_id' => $slot->slot_id, // Optional: if we want to link explicitly in DB
                        ]);
                    }
                }
            }
        }
    }
}
