<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use App\Models\Member\Member;
use App\Models\Finance\Subscription;
use App\Models\Member\AccessBadge;
use App\Models\Finance\Plan;
use App\Models\Activity\Activity;
use App\Models\Finance\Payment;
use App\Models\Admin\AccessLog;
use App\Models\Staff\Staff;
use Carbon\Carbon;

class TestDataSetSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create('fr_FR');

        // Prerequisites
        $plans = Plan::where('is_active', true)->get();
        $activities = Activity::where('is_active', true)->get();
        $staff = Staff::first(); // Assuming at least one staff exists
        $timeSlots = DB::table('pool_schema.time_slots')->get();

        if ($plans->isEmpty() || $activities->isEmpty() || !$staff) {
            $this->command->warn('Missing plans, activities, or staff. Please seed them first.');
            return;
        }

        $staffId = $staff->staff_id;

        // Helper to create member
        $createMember = function () use ($faker) {
            return Member::create([
                'first_name' => $faker->firstName,
                'last_name' => $faker->lastName,
                'email' => $faker->unique()->safeEmail,
                'phone_number' => $faker->phoneNumber,
                'date_of_birth' => $faker->date('Y-m-d', '-18 years'),
                'address' => $faker->address,
                'created_at' => now()->subDays(rand(1, 60)),
            ]);
        };

        // Helper to create badge
        $createBadge = function ($memberId) use ($faker) {
            AccessBadge::create([
                'member_id' => $memberId,
                'badge_uid' => strtoupper($faker->bothify('BADGE-####-????')),
                'status' => 'active',
                'issued_at' => now()->subDays(rand(1, 60)),
            ]);
        };

        // Helper to create subscription
        $createSubscription = function ($memberId, $status = 'active', $isMonthly = true) use ($plans, $activities, $faker) {
            $plan = $plans->where('plan_type', $isMonthly ? 'monthly_weekly' : 'per_visit')->random() ?? $plans->random();
            $activity = $activities->random();
            
            $startDate = $status === 'active' ? Carbon::now()->subDays(rand(0, 20)) : Carbon::now()->subMonths(rand(2, 5));
            $endDate = $startDate->copy()->addMonths($plan->duration_months ?? 1);

            return Subscription::create([
                'member_id' => $memberId,
                'plan_id' => $plan->plan_id,
                'activity_id' => $activity->activity_id,
                'start_date' => $startDate,
                'end_date' => $endDate,
                'status' => $status === 'active' && $endDate->isPast() ? 'expired' : $status,
                'visits_per_week' => $plan->visits_per_week,
            ]);
        };

        // Helper to create payment
        $createPayment = function ($subscription) use ($faker, $staffId) {
            Payment::create([
                'subscription_id' => $subscription->subscription_id,
                'amount' => $subscription->plan->price,
                'payment_date' => $subscription->start_date,
                'payment_method' => $faker->randomElement(['cash', 'card', 'transfer']),
                'received_by_staff_id' => $staffId,
                'notes' => 'Payment generated by seeder',
            ]);
        };

        // Helper to generate logs
        $generateLogs = function ($member, $subscription) use ($faker, $timeSlots) {
            $numLogs = rand(5, 15);
            for ($i = 0; $i < $numLogs; $i++) {
                $logDate = Carbon::instance($subscription->start_date)->addDays(rand(0, $subscription->start_date->diffInDays(now()->min($subscription->end_date))));
                
                // Find a slot for this day if possible, or pick random
                $dayOfWeek = $logDate->dayOfWeekIso; // 1 (Mon) - 7 (Sun)
                $slot = $timeSlots->where('weekday_id', $dayOfWeek)->first();
                
                $logTime = $logDate->copy()->setTime(rand(8, 20), rand(0, 59));
                if ($slot) {
                    $logTime = $logDate->copy()->setTimeFromTimeString($slot->start_time)->addMinutes(rand(0, 30));
                }

                DB::table('pool_schema.access_logs')->insert([
                    'member_id' => $member->member_id,
                    'badge_uid' => $member->accessbadge->badge_uid ?? 'UNKNOWN',
                    'access_decision' => 'granted',
                    'access_time' => $logTime,
                    'activity_id' => $subscription->activity_id,
                    'subscription_id' => $subscription->subscription_id,
                    'slot_id' => $slot ? $slot->slot_id : null,
                ]);
            }
        };

        // === 1. Active Monthly/Weekly (15 members) ===
        for ($i = 0; $i < 15; $i++) {
            $member = $createMember();
            $createBadge($member->member_id);
            $sub = $createSubscription($member->member_id, 'active', true);
            $createPayment($sub);
            $generateLogs($member, $sub);
        }

        // === 2. Active Per Visit (10 members) ===
        for ($i = 0; $i < 10; $i++) {
            $member = $createMember();
            $createBadge($member->member_id);
            $sub = $createSubscription($member->member_id, 'active', false);
            $createPayment($sub);
            $generateLogs($member, $sub);
        }

        // === 3. Expired (10 members) ===
        for ($i = 0; $i < 10; $i++) {
            $member = $createMember();
            $createBadge($member->member_id);
            $sub = $createSubscription($member->member_id, 'expired', true);
            $createPayment($sub);
            // Logs only during active period
            $generateLogs($member, $sub);
        }

        // === 4. Multiple Subscriptions (5 members) ===
        for ($i = 0; $i < 5; $i++) {
            $member = $createMember();
            $createBadge($member->member_id);
            
            // Old expired one
            $oldSub = $createSubscription($member->member_id, 'expired', true);
            $createPayment($oldSub);
            $generateLogs($member, $oldSub);

            // New active one
            $newSub = $createSubscription($member->member_id, 'active', true);
            $createPayment($newSub);
            $generateLogs($member, $newSub);
        }

        // === 5. No Subscription / New Members (10 members) ===
        for ($i = 0; $i < 10; $i++) {
            $member = $createMember();
            // 50% chance of having a badge
            if (rand(0, 1)) {
                $createBadge($member->member_id);
                // Generate a denied log
                DB::table('pool_schema.access_logs')->insert([
                    'member_id' => $member->member_id,
                    'badge_uid' => $member->accessbadge->badge_uid,
                    'access_decision' => 'denied',
                    'denial_reason' => 'Aucun abonnement actif',
                    'access_time' => now()->subDays(rand(0, 5)),
                ]);
            }
        }

        $this->command->info('Successfully generated comprehensive test dataset.');
    }
}
